fabiocolacio/Marker

gres/marker-prefs-window.ui
gres/marker-prefs-window.ui~
src/marker-editor-window.c
src/marker-prefs.c

* Improved look
* 'none' option added for css-theme selection

Improve preferences dialog

---

src/marker-prefs.c
src/marker-source-view.c
src/resources/ui/prefs-window.ui

I updated the preference ui using the gedit style.

Ui prefs update

---

meson.build
src/marker-preview.c
src/marker.c
src/webkit-extension/scroll-extension.c
src/webkit-extension/scroll-extension.h

Simple web extension to fix to issue #13

WebExtension to keep scroll position fixed

---

data/com.github.fabiocolacio.marker.gschema.xml
src/marker-editor-window.c
src/marker-editor-window.h
src/marker-prefs.c
src/marker-prefs.h
src/marker-source-view.h
src/resources/ui/prefs-window.ui

* Finished implementing various features that were halfway implemented
* Improved the look and consistency of the preferences window
Resolved issue #55.

Prefs work

---

src/marker-editor-window.c
src/marker-editor-window.h
src/resources/ui/shortcuts-window.ui

This is a simple fullscreen mode, and a good first step towards adding feature #48

Added fullscreen mode

---

src/marker-editor-window.c
src/resources/ui/shortcuts-window.ui

Add shortcuts for "close document" and "quit application"

---

src/marker-editor-window.c
src/marker-preview.c
src/marker-preview.h
src/resources/marker.gresource.xml
src/resources/ui/editor-window.ui
src/resources/ui/gear-popover-full.ui
src/resources/ui/gear-popover.ui

Add zoom controls in the gear popover menu

---

meson.build
src/hoedown/charter/charter.c
src/hoedown/charter/charter.h
src/hoedown/charter/clist.c
src/hoedown/charter/clist.h
src/hoedown/charter/parser.c
src/hoedown/charter/renderer.c
src/hoedown/charter/svg_utils.c
src/hoedown/charter/svg_utils.h
src/hoedown/charter/tinyexpr/tinyexpr.c
src/hoedown/charter/tinyexpr/tinyexpr.h
src/hoedown/document.c
src/marker-source-view.c
src/marker.c
src/resources/marker.gresource.xml
src/resources/ui/editor-window.ui
src/resources/ui/marker-appmenu.ui

Updating sketcher branch codebase before joining the master

Using updated codebase for sketcher

---

com.github.fabiocolacio.marker.json

I also added some comments to explane what need to be changed flathub inside the manifest.

[minor] removed dbus access from flatpak

---

src/marker-window.c

The ability to open the same file twice can lead to data loss (or at least encourage it). This patch switches to the relevant editor if we attempt to open a file that is already open.
Reason for this patch:
I tend to collapse the left tab pane because I don't like the wasted space. Earlier today, I accidentally opened the same file twice, and did my work in the second editor without knowing about the first. When I discovered the first editor again after showing the left pane, in my haste I foolishly confused the two and wound up closing the second editor.

Don't open same file twice.

---

data/common/scidown.css

I fixed #184 , can you please test this too?

fixed #184

---

src/marker-window.c

Replace empty untitled documents with newly opened file

---

com.github.fabiocolacio.marker.json

This makes it easy to build Marker using GNOME Builder.

Add Flatpak manifest

---

meson.build
po/LINGUAS
po/POTFILES
po/fr.po
po/marker.pot
po/meson.build
src/marker-editor.c
src/marker.c
src/resources/ui/marker-appmenu.ui
src/resources/ui/marker-gear-popover.ui
src/resources/ui/marker-headerbar.ui
src/resources/ui/marker-prefs-window.ui
src/resources/ui/marker-shortcuts-window.ui
src/resources/ui/marker-sketcher-window.ui

I didn't test them because the nightly GNOME Builder fails to export the flatpak bundle for no reason, but it should work
The .pot file can be update with the command
`ninja -C _build marker-update-po` (where _build is your build directory)

Add translations (#241)

---

src/marker-preview.c

When the user opens a link in the webkit view the request is catched and
send to the default browser then the click is ignored in webkit.
This solves the error users get when they click links, when Marker runs
inside flatpak (without network access), because this way Marker doesn't make
a network connection, see #231.

improve how links are opened when clicked fix #231

---

README.md

Marker available in official Fedora repos now. 🎉

Update Fedora package info

---

src/marker-preview.c

Read the actual translation from gtk3 localization.

Fix PDF export on non-English locales

---

meson.build

Forwarded from https://github.com/void-linux/void-packages/blob/6e9ceae5a9a1e35ef75bfa16cabc56b6ffe89e76/srcpkgs/Marker/patches/elf_files_in_lib.patch
Fixes #293

Install ELF file into lib

---

src/resources/ui/marker-shortcuts-window.ui

Mark "Draw a sketch" as translatable

---

data/styles/GithubDark.css
data/styles/README.md

Add Dark theme from OzakIOne
OzakIOne/markdown-github-dark@13b4487925e855a484984ed35ff54b6803fcff35

Add GitHub Dark theme

---

data/styles/GitHub2.css

Now it's a little more like GitHub

Underline the H3 titles

---

debian/changelog
debian/control

And also changed version number (20.04.04 -> 20.04.04.2) in the daily builds PPA.

Updated webkit version in debian package

---

data/styles/Nord.css

I added the [Nord](https://www.nordtheme.com/) theme for Marker. Suggestions and improvements are welcome, this is my very first css sheet!
Screenshots:

Created Nord.css
