fabiocolacio/Marker

src/marker-markdown.c

Hi, I added the mathjax script to the generated html to view latex formula in _Marker_ as shown in the picture below:
However due to the fast refresh rate (at each typing if I well understood) sometimes mathjax doesn't have the time to refresh the preview. I think that just adding some small minimum refresh interval would be sufficient to have a fluid preview and a correct rendering of the formula.
Cheers,
Martino

Initial mathjax support

---

data/com.github.fabiocolacio.marker.gschema.xml
meson.build
src/hoedown/html.c
src/hoedown/html.h
src/marker-editor-window.c
src/marker-markdown.c
src/marker-prefs.c
src/marker-prefs.h
src/marker-preview.c
src/marker-string.c
src/marker-string.h
src/marker-widget.c
src/resources/ui/prefs-window.ui

Patch to close issue #61 
**Note**: I included ```marker-prefs.h``` in ```marker-markdown.c``` to avoid to add a new argument to all the functions (in this way I retrieve the highlight theme directly in the function).
If you prefer to add an argument instead just tell me.

Added possibility to switch between highligth.js themes

---

data/com.github.fabiocolacio.marker.gschema.xml
data/styles/GitHub.css
data/styles/GitHub2.css
data/styles/Solarized (Dark).css
data/styles/Solarized (Light).css
data/styles/markdown.css
data/styles/screen.css
data/styles/swiss.css
src/hoedown/html.c
src/hoedown/html.h
src/marker-markdown.c
src/marker-prefs.c
src/marker-prefs.h
src/resources/ui/prefs-window.ui

I added a small feature to hoedown to display the title or the alt text of an image as caption:
```markdown
Image with title:
Image with only alt text:
```
Moreover I added the option to numbering the figure (and use the number as id of the html block).
**Figure caption and numbering enabled**
**Figure caption enabled, numbering disabled**
**Figure caption and numbering disabled**
To nicely render the caption I modified some (or all?) css theme to align the figure caption to the centre and use a smaller font.

Figure Caption and Numbering added to Hoedown

---

data/com.github.fabiocolacio.marker.gschema.xml
src/hoedown/html.c
src/hoedown/html.h
src/marker-markdown.c
src/marker-prefs.c
src/marker-prefs.h
src/resources/ui/prefs-window.ui

An addition extension to hoedown after #84  is to add a simple equation counter in the equation block:
There is a check button in the preferences and by default is disabled.

Equation numbering (sequential to #84)

---

data/com.github.fabiocolacio.marker.appdata.xml

Fixes some minor things in the appdata file (added missing developer name and email address, removed hyperlinks).
It now passes validate-relax, which should be enough to get it published. There are still some non-critical issues, like the size of the screenshots, but that can be addressed later.
#122

Minor appdata fixes for Flathub

---

data/com.github.fabiocolacio.marker.appdata.xml

Until this [upstream commit](https://github.com/flatpak/flatpak/commit/6ab657b9100427f3c4c0f19f8695b7b71a417f49) flatpak wouldn't export appdata from any app that didn't end it's appdata ID with .desktop. This would prevent your app from showing up in software stores or any other UIs for Flathub.
This commit changes the app ID but makes sure that the appdata file still provides the old ID to cover any existing command line installs.
The second commit adds OARS metadata, which flatpak encourages and makes sure your app is correctly categorised.
This has been [patched in Flathub ](https://github.com/flathub/com.github.fabiocolacio.marker/pull/1)as it's the only way to get the app to show up correctly until clients are updated.

Fix flatpak visibility in software stores

---

post-install.sh

Basically distros want to compile gschemas and update the icon cache themselves and not have it done via a post-install script

don't run post-install.sh when creating distro packages

---

data/common/scidown.css
data/styles/Solarized (Dark).css

Hey, I added support for languages you write from right to left(eg. Hebrew, Arabic, Persian).
I only did it for one file for now because I don't have a lot of time at this moment, but I wanted your approval and adding this CSS rule won't be a problem later to all the files.
[unicode-bidi MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/unicode-bidi)
_tl;dr_ with the value "plaintext", it will change the direction of the text based on the language of the sentence.

Added RTL Support 

---

data/com.github.fabiocolacio.marker-symbolic.svg
data/com.github.fabiocolacio.marker.svg

- GNOME 3.32 redesign of app icons.
See https://gitlab.gnome.org/GNOME/Initiatives/issues/2
for more info.
Closes https://github.com/fabiocolacio/Marker/issues/243

data: Update icons to 3.32 style

---

meson.build

Tiny change. From
`/usr/share/appdata/%{id}.appdata.xml`
to
`/usr/share/metainfo/%{id}.appdata.xml`
https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

The Appdata files now go to /usr/share/metainfo

---

README.md
docs/index.html

The Flathub links still point to [beta.flathub.org](https://beta.flathub.org/) which does not exist any more. They should point to the respective page on [flathub.org](https://flathub.org/) instead.
This also resolves #270.

Fix Flathub links

---

data/scripts/mathjax/extensions/a11y/mathmaps/.htaccess

Can we safely delete this file?
`scripts/mathjax/extensions/a11y/mathmaps/.htaccess`
PS: some linters consider this an error
`E: htaccess-file /usr/share/com.github.fabiocolacio.marker/scripts/mathjax/extensions/a11y/mathmaps/.htaccess`

Remove .htaccess file

---

src/marker-window.c

Solves #331.
This MR changes the exit dialog from INFORMATIONAL to WARNING type and switches the generic CANCEL_OK for more descrete and specific text "Cancel" and "Discard".

#331 Informative exit message buttons

---

src/marker-exporter.c

Quoting is necesary if path has unconvenient characters like spaces.
Fixes #363

Quote paths in pandoc command

---

README.md

Marker present and published in stable Flathub channel, Flathub Beta links do not have landing pages, which results in a 404 when opened in browser, changed link to point to stable release on Flathub.

Update Flathub Link

---

data/com.github.fabiocolacio.marker.gschema.xml
src/marker-prefs.c
src/marker-prefs.h
src/marker-window.c

This pull request build on #312.
The window width and height is saved in the preferences when the window is closed, and is restored at the start of the program.
These changes partially solve issue #309.

Remember window size

---

data/com.github.fabiocolacio.marker.gschema.xml
src/marker-editor.c
src/marker-editor.h
src/marker-prefs.c
src/marker-prefs.h
src/marker-window.c

These changes add features requested in issue #309, specifically window position and sidebar open/closed state.
Editor pane width is remembered too, so it is possible to "split the window always at 50%" (if you don't resize the window),
which was also requested in the issue.

Save window position, editor pane width and sidebar open/closed state in the preferences

---

meson.build

webkit2gtk-4.1 is compatible with webkit2gtk-4.0, the difference is that it links with libsoup3 instead of libsoup2.
It is required for bumping the flatpak's runtime to GNOME 43.

meson: Bump webkit2gtk dependency to 4.1

---

data/com.github.fabiocolacio.marker.appdata.xml
po/POTFILES
po/marker.pot
src/marker-exporter.c
src/marker-window.c

Please review individually. 
- gschema.xml contains numerous strings. We might consider omitting them due to their low priority in translation.
- I encountered difficulties while attempting to build Marker because the flatpak manifest was outdated.

Several translation related patches

---

data/com.github.fabiocolacio.marker.appdata.xml

It appears that the appstream project no longer supports `translatable=no` properties, and gettext extract the `translatable=no` marked strings as translatable.
I opened an issue to inform about the situation, but `translatable=no` properties are not accepted by developers. You can find the issue here: https://github.com/ximion/appstream/issues/623
**Please test your script or string extraction process before merging this PR.**
> In MetaInfo files, each individual paragraph of a description
> (or enumerated entry) is translated individually, however,
> you can only exclude the complete block from being translated
> by adding `translate="no"` to the description element.
Source: https://freedesktop.org/software/appstream/docs/sect-Quickstart-Translation.html
- Fix broken markup in li tag
- …

appdata: `translate=no` properties and appdata improvements
